server.port=9042

spring.datasource.url=${ECOTRACK_DB_URL:jdbc:mysql://localhost:3306/ecotrack}
spring.datasource.username=${ECOTRACK_DB_USERNAME:root}
spring.datasource.password=${ECOTRACK_DB_PASSWORD:Punith@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

ecotrack.jwt.secret=${ECOTRACK_JWT_SECRET:ThisIsMyVeryLongSecretKeyForJwtAuthentication123456789}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
