server.port=9042

spring.datasource.url=jdbc:mysql://localhost:3306/ecotrack
spring.datasource.username=root
spring.datasource.password=Punith@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true